import {
  buttonBg,
  buttonBorder,
  darkBlack,
  lightBlue,
  nunitobold,
  buttonTextColor,
  buttonbg,
  buttonRipple,
  fontQsbold,
  darkWhite,
  darkBlue,
  darkRed,
  mariner,
  disablebtn,
} from 'helpers/variables';

export const buttonStyles = {
  labelStyle: {
    backgroundColor: mariner,
    color: buttonTextColor,
    height: '70px',
    letterSpacing: '2px',
    borderRadius: '0px',
    padding: '0px 15px',
    fontFamily: fontQsbold,
    fontSize: '12px',
    maxWidth: '340px',
    textTransform: 'uppercase',
    lineHeight: '50px',
    opacity: 0.15,
  },
  primaryLabel: {
    border: '1px',
    borderColor: mariner,
    backgroundColor: buttonbg,
    color: buttonTextColor,
    height: '50px',
    letterSpacing: '1px',
    borderRadius: '22px',
    padding: '17px 5px',
    fontFamily: nunitobold,
    fontWeight: 'bold',
    fontSize: '14px',
    minWidth: '100%',
    textTransform: 'capitalize',
    lineHeight: '14px',
    zIndex: 0,
  },
  disableLabel: {
    border: '1px',
    borderColor: mariner,
    backgroundColor: disablebtn,
    color: darkWhite,
    height: '50px',
    letterSpacing: '1px',
    borderRadius: '22px',
    padding: '17px 5px',
    fontFamily: nunitobold,
    fontWeight: 'bold',
    fontSize: '14px',
    minWidth: '100%',
    textTransform: 'capitalize',
    lineHeight: '14px',
    zIndex: 0,
  },
  secondaryLabel: {
    border: '2px solid',
    borderColor: buttonBorder,
    backgroundColor: darkWhite,
    color: buttonTextColor,
    height: '50px',
    letterSpacing: '1px',
    borderRadius: '22px',
    padding: '17px 5px',
    fontFamily: nunitobold,
    fontWeight: 'bold',
    fontSize: '14px',
    minWidth: '100%',
    textTransform: 'capitalize',
    lineHeight: '14px',
    zIndex: 0,
  },
  facebookLable: {
    backgroundColor: darkBlue,
    color: darkWhite,
    height: '50px',
    letterSpacing: '2px',
    borderRadius: '0px',
    padding: '0px 15px',
    fontFamily: fontQsbold,
    fontSize: '12px',
    maxWidth: '340px',
    textTransform: 'uppercase',
    lineHeight: '50px',
    marginBottom: '25px',
  },
  googleLable: {
    backgroundColor: darkRed,
    color: darkWhite,
    height: '50px',
    letterSpacing: '2px',
    borderRadius: '0px',
    padding: '0px 15px',
    fontFamily: fontQsbold,
    fontSize: '12px',
    maxWidth: '340px',
    textTransform: 'uppercase',
    lineHeight: '50px',
  },
};

export const rippleColor = buttonRipple;
export const hoverColor = darkWhite;
export const hoverColorBlack = darkBlack;
